// <auto-generated />
using CodingWiki_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodingWiki_DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250724164933_Rename_Table_name_Genres-to-Category")]
    partial class Rename_Table_name_GenrestoCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodingWiki_Model.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 5)
                        .HasColumnType("decimal(10,5)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            ISBN = "12525",
                            Price = 10.25m,
                            Title = "MyStroy"
                        },
                        new
                        {
                            BookId = 2,
                            ISBN = "85485",
                            Price = 559.27m,
                            Title = "NASA"
                        },
                        new
                        {
                            BookId = 3,
                            ISBN = "1995",
                            Price = 6.14m,
                            Title = "MakeMyTrip"
                        },
                        new
                        {
                            BookId = 4,
                            ISBN = "2022",
                            Price = 85.56m,
                            Title = "Google"
                        },
                        new
                        {
                            BookId = 5,
                            ISBN = "20254",
                            Price = 17.2m,
                            Title = "MSTeams"
                        },
                        new
                        {
                            BookId = 6,
                            ISBN = "2055",
                            Price = 5874.27m,
                            Title = "FitApp"
                        },
                        new
                        {
                            BookId = 7,
                            ISBN = "7845",
                            Price = 121.25m,
                            Title = "Paytm"
                        },
                        new
                        {
                            BookId = 8,
                            ISBN = "7452",
                            Price = 879.27m,
                            Title = "Gpay"
                        });
                });

            modelBuilder.Entity("CodingWiki_Model.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
