// <auto-generated />
using System;
using CodingWiki_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodingWiki_DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250818102631_Add-BookAuthorMap")]
    partial class AddBookAuthorMap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodingWiki_Model.Models.Author", b =>
                {
                    b.Property<int>("Author_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Author_Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Author_Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("CodingWiki_Model.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("BookDetail_Id")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 5)
                        .HasColumnType("decimal(10,5)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("BookDetail_Id")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookDetail_Id = 1,
                            ISBN = "12525",
                            Price = 10.25m,
                            Title = "MyStroy"
                        },
                        new
                        {
                            BookId = 2,
                            BookDetail_Id = 2,
                            ISBN = "85485",
                            Price = 559.27m,
                            Title = "NASA"
                        },
                        new
                        {
                            BookId = 3,
                            BookDetail_Id = 3,
                            ISBN = "1995",
                            Price = 6.14m,
                            Title = "MakeMyTrip"
                        },
                        new
                        {
                            BookId = 4,
                            BookDetail_Id = 4,
                            ISBN = "2022",
                            Price = 85.56m,
                            Title = "Google"
                        },
                        new
                        {
                            BookId = 5,
                            BookDetail_Id = 5,
                            ISBN = "20254",
                            Price = 17.2m,
                            Title = "MSTeams"
                        },
                        new
                        {
                            BookId = 6,
                            BookDetail_Id = 6,
                            ISBN = "2055",
                            Price = 5874.27m,
                            Title = "FitApp"
                        },
                        new
                        {
                            BookId = 7,
                            BookDetail_Id = 7,
                            ISBN = "7845",
                            Price = 121.25m,
                            Title = "Paytm"
                        },
                        new
                        {
                            BookId = 8,
                            BookDetail_Id = 8,
                            ISBN = "7452",
                            Price = 879.27m,
                            Title = "Gpay"
                        });
                });

            modelBuilder.Entity("CodingWiki_Model.Models.BookAuthorMap", b =>
                {
                    b.Property<int>("Author_Id")
                        .HasColumnType("int");

                    b.Property<int>("Book_Id")
                        .HasColumnType("int");

                    b.HasIndex("Author_Id");

                    b.HasIndex("Book_Id");

                    b.ToTable("BookAuthorMaps");
                });

            modelBuilder.Entity("CodingWiki_Model.Models.BookDetail", b =>
                {
                    b.Property<int>("BookDetail_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookDetail_Id"));

                    b.Property<int>("NumberOfChapters")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookDetail_Id");

                    b.ToTable("BookDetails");

                    b.HasData(
                        new
                        {
                            BookDetail_Id = 1,
                            NumberOfChapters = 10,
                            NumberOfPages = 100,
                            Weight = "1kg"
                        },
                        new
                        {
                            BookDetail_Id = 2,
                            NumberOfChapters = 12,
                            NumberOfPages = 120,
                            Weight = "1.2kg"
                        },
                        new
                        {
                            BookDetail_Id = 3,
                            NumberOfChapters = 8,
                            NumberOfPages = 80,
                            Weight = "0.8kg"
                        },
                        new
                        {
                            BookDetail_Id = 4,
                            NumberOfChapters = 15,
                            NumberOfPages = 150,
                            Weight = "1.5kg"
                        },
                        new
                        {
                            BookDetail_Id = 5,
                            NumberOfChapters = 20,
                            NumberOfPages = 200,
                            Weight = "2kg"
                        },
                        new
                        {
                            BookDetail_Id = 6,
                            NumberOfChapters = 18,
                            NumberOfPages = 180,
                            Weight = "1.8kg"
                        },
                        new
                        {
                            BookDetail_Id = 7,
                            NumberOfChapters = 22,
                            NumberOfPages = 220,
                            Weight = "2.2kg"
                        },
                        new
                        {
                            BookDetail_Id = 8,
                            NumberOfChapters = 25,
                            NumberOfPages = 250,
                            Weight = "2.5kg"
                        });
                });

            modelBuilder.Entity("CodingWiki_Model.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CodingWiki_Model.Models.Publisher", b =>
                {
                    b.Property<int>("Publisher_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Publisher_Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Publisher_Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("CodingWiki_Model.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategory_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategory_Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SubCategory_Id");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("CodingWiki_Model.Models.Book", b =>
                {
                    b.HasOne("CodingWiki_Model.Models.BookDetail", "BookDetail")
                        .WithOne("Book")
                        .HasForeignKey("CodingWiki_Model.Models.Book", "BookDetail_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookDetail");
                });

            modelBuilder.Entity("CodingWiki_Model.Models.BookAuthorMap", b =>
                {
                    b.HasOne("CodingWiki_Model.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("Author_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodingWiki_Model.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CodingWiki_Model.Models.BookDetail", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
